image: golang:latest

stages:
  - validate
  - build

fmt:
  stage: validate
  script:
    - gofmt -l -s -e .
    - exit $(gofmt -l -s -e . | wc -l)

vet:
  stage: validate
  script:
    - go vet -composites=false ./...

test:
  stage: validate
  script:
    - go test -race -v ./...

build-netris:
  stage: build
  script:
    - cd cmd/netris
    - go build

build-netris-server:
  stage: build
  script:
    - cd cmd/netris-server
    - go build
